name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.ROOT }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /root/Syncmed-Healthcare
            git pull origin main
            npm install
            npm run build
            pm2 restart syncmed